# Generated by Django 2.1.5 on 2020-04-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeDir', '0002_newpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='category',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
