# Generated by Django 2.1.5 on 2020-04-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeDir', '0003_newpost_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mainpost',
            name='category',
        ),
        migrations.AlterField(
            model_name='mainpost',
            name='content',
            field=models.TextField(verbose_name='Yazı'),
        ),
        migrations.AlterField(
            model_name='mainpost',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Başlık'),
        ),
        migrations.DeleteModel(
            name='NewPost',
        ),
    ]
