# Generated by Django 2.1.5 on 2020-04-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeDir', '0005_auto_20200423_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Resim'),
        ),
    ]
