# Generated by Django 2.1.5 on 2020-04-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeDir', '0006_auto_20200423_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpost',
            name='image',
        ),
        migrations.AddField(
            model_name='mainpost',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link'),
        ),
    ]
