# Generated by Django 2.1 on 2020-04-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeDir', '0007_auto_20200423_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpost',
            name='tag',
            field=models.TextField(blank=True, null=True, verbose_name='Tag - #'),
        ),
        migrations.AlterField(
            model_name='mainpost',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link (https://...)'),
        ),
    ]
